### ISSUE TITLE
Improving codegen test results

### ISSUE THREAD

**Issue by JordanMartinez** [purefunctor/purs-backend-chez#2]
I'm somewhat following along with your work here. However, without a PureScript source file to use as my mental model for what's being input into the codegen, I'm not sure what the corefn you have stored in a String represents.

Thoughts on duplicating what's done in [`purs-backend-es`](https://github.com/aristanetworks/purescript-backend-optimizer/blob/main/backend-es/test/Main.purs#L68-L155) to test the codegen of this backend?

**Comment by purefunctor** [comment]
Yup, I can work on adding snapshot tests for this. Right now I'm just manually compiling test cases and copying the corefn into `Main.purs`, which isn't particularly efficient, but probably should be changed
